import type { Metadata } from 'next';
import { SiteFooter } from '@/components/site-footer';
import { SiteHeader } from '@/components/site-header';

export const metadata: Metadata = { title: 'Política de privacidade | Cognitia', description: 'Informações sobre privacidade e tratamento de dados no site da Cognitia.', alternates: { canonical: '/privacidade' }, robots: { index: true, follow: true } };

export default function PrivacyPage() {
  return <main className="inner-main"><SiteHeader /><article className="page-shell legal-content"><p className="eyebrow">Privacidade</p><h1>Política de privacidade</h1><p>Última atualização: 2 de setembro de 2026.</p><p>Esta política descreve como a Cognitia trata informações fornecidas por visitantes do site e por pessoas que iniciam contato pelos canais disponibilizados.</p><h2>1. Dados que podem ser tratados</h2><p>O site não exige cadastro. Quando você entra em contato por e-mail, telefone, WhatsApp ou redes sociais, os dados enviados voluntariamente — como nome, empresa, telefone, e-mail e descrição do desafio — podem ser utilizados para responder à solicitação e manter o relacionamento comercial.</p><h2>2. Finalidades</h2><ul><li>Responder dúvidas e solicitações;</li><li>Avaliar oportunidades de projetos e parcerias;</li><li>Manter registros de comunicação necessários ao relacionamento;</li><li>Cumprir obrigações legais e proteger direitos.</li></ul><h2>3. Compartilhamento</h2><p>Os dados não são comercializados. Eles podem ser tratados por prestadores necessários à comunicação, hospedagem e operação dos canais utilizados, observadas as finalidades desta política e as regras aplicáveis.</p><h2>4. Links e serviços externos</h2><p>O site contém links para WhatsApp, LinkedIn, Instagram, Google Maps e outros sites. O tratamento realizado por esses serviços segue as respectivas políticas de privacidade.</p><h2>5. Segurança e retenção</h2><p>A Cognitia adota medidas razoáveis para proteger as informações sob sua responsabilidade e conserva os dados pelo tempo necessário às finalidades descritas ou ao cumprimento de obrigações legais.</p><h2>6. Direitos do titular</h2><p>Nos termos da LGPD, você pode solicitar confirmação de tratamento, acesso, correção, eliminação quando aplicável e outras informações previstas em lei.</p><h2>7. Contato</h2><p>Para dúvidas ou solicitações relacionadas a dados pessoais, escreva para <a href="mailto:contato@cognitiasolucoes.com">contato@cognitiasolucoes.com</a>.</p></article><SiteFooter /></main>;
}
